Added api endpoint for aggregation by day
biodiv-platform/biodiv-esmodule pull request #97
Opened 2024-09-18 11:50 UTC by rishitha-ravi

2024-10-10 11:18 UTC, arunasd463 commented on src/main/java/com/strandls/esmodule/controllers/ESController.java
> +	@ApiOperation(value = "Aggregation for List Page", notes = "Returns Aggregated values", response = Map.class)
give meaningful value and notes , it will be useful when using swagger-ui and also other devs would understand this easily.

2024-10-10 11:22 UTC, arunasd463 commented on src/main/java/com/strandls/esmodule/controllers/ESController.java
Format the code by `ctrl+shift+f` in eclipse

2024-10-10 11:23 UTC, arunasd463 commented on src/main/java/com/strandls/esmodule/controllers/ESController.java
> +	@ApiOperation(value = "Aggregation for List Page", notes = "Returns Aggregated values", response = Map.class)
Give meaningful message here too.

2024-10-10 11:28 UTC, arunasd463 commented on src/main/java/com/strandls/esmodule/services/impl/ElasticSearchServiceImpl.java
> +			Histogram dateHistogram = response.getAggregations().get("agg");
add "agg" to constants and reuse it.

2024-10-10 11:42 UTC, arunasd463 commented on src/main/java/com/strandls/esmodule/services/impl/ElasticSearchServiceImpl.java
> +	public Map<String, List<Map<String, Object>>> aggregationByMonth(String user) throws IOException {
can we get this "extended_observation"  form controller , make it more generic like other endpoints?

2024-10-10 11:48 UTC, arunasd463 requested changes
Few changes required.

2024-10-11 06:17 UTC, rishitha-ravi commented on src/main/java/com/strandls/esmodule/services/impl/ElasticSearchServiceImpl.java
> +			aggregation = AggregationBuilders.dateHistogram("agg").field("created_on").dateHistogramInterval(DateHistogramInterval.days(1)).format("yyyy-MM-dd");
Changed it to calendarInterval

2024-10-14 12:22 UTC, closed without merging